lokamanya_vidya_mandir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('supervisor_portal/', include('supervisor_portal.urls'))
]

supervisor_portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.render_landing_page),
	path("login", views.log_user_in),
	path("logout", views.logout_user),
	path("create_record", views.create_record),
	path("modify_record", views.modify_record),
	path("edit_record", views.edit_record),
	path("test", views.test, name="test")
]

supervisor_portal/models.py
from django.db import models
import datetime

# Create your models here.
class Ticket(models.Model):
	STATUS_CHOICES = (
		("PENDING", "PENDING"),
		("RESOLVED", "RESOLVED")
	)
	raised_by = models.CharField(max_length = 30)
	body = models.TextField()
	status = models.CharField(max_length = 1, choices = STATUS_CHOICES, default = "PENDING")
	date_of_raising = models.DateTimeField(auto_now = True)
	date_of_resolving = models.DateTimeField(null = True)
	
	def mark_resolved(self):
		if self.status == "PENDING":
			self.status = "RESOLVED"
			self.date_of_resolving = datetime.datetime.now()
			self.save()
			return "Ticket (" + self.id + ") has been marked as resolved."
		else:
			raise Exception("This Ticket (" + self.id + ") was already resolved.")
			
			
class Record(models.Model):
	for_floor = models.IntegerField()
	for_room = models.CharField(max_length=10)
	body = models.TextField()
	date = models.DateField(auto_now = True)
	

supervisor_portal/forms.py
from django.forms import ModelForm
from .models import Record, Ticket

class RecordForm(ModelForm):
	class Meta:
		model = Record
		fields = ["for_floor", "for_room", "body"]

supervisor_portal/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .forms import RecordForm
from .models import Record
import datetime

def render_landing_page(request):
	if request.user.is_authenticated:
		return render_userpage(request)
	else:
		return render(request, "landing.html")

	
def log_user_in(request):
	if request.method == "POST" and not request.user == "AnonymousUser":	
		user = authenticate(request, username = request.POST.get("username"), password = request.POST.get("password"))
		if user is not None:
			login(request, user)
			return render_userpage(request)
		else:
			return render(request, "landing.html", {"message": "Incorrect Username or Password!"})
	elif request.user.is_authenticated:
		user = User.objects.get(username = request.user)
		return render_userpage(request)
	
	
def render_userpage(request, message=None):
	if request.user.is_authenticated:
		user = User.objects.get(username = request.user)
		user_groups = [ group["name"] for group in user.groups.all().values() ]
		if "management" in user_groups:
			form = RecordForm()
			return render(request, "userpage.html", {"user": user, "record_form": form, "message": message})
		elif "trustee" in user_groups:
			try:
				records = Record.objects.all()[-1:-10]
			except Exception as e:
				records = Record.objects.all()
			#if len(records) == 0:
			#	message = "-- No Records To Show Yet --"
			return render(request, "userpage.html", {"records": records, "message": message})
		else:
			return render(request, "userpage.html", {"user": use, "message": message})
	
	
def logout_user(request):
	if request.user.is_authenticated and request.method == "POST":
		logout(request)
		return render_landing_page(request)
	
	
def create_record(request):
	floor = request.POST.get("for_floor")
	room = request.POST.get("for_room")
	body = request.POST.get("body")
	Record.objects.create(
		for_floor = floor,
		for_room = room,
		body = body
	)
	return redirect("/supervisor_portal/")
	
	
def modify_record(request):
	if request.user.is_authenticated:
		action = request.POST.get("action")
		record_id = request.POST.get("record_id")
		if action == "edit":
			record_to_edit = Record.objects.get(id = record_id)
			form = RecordForm()
			return render(request, "userpage.html", {"record_to_edit": record_to_edit})
		else:
			record_to_delete = Record.objects.get(id = record_id)
			record_to_delete.delete()
			return render_userpage(request, "Record Deleted Successfully!")
		
		
def edit_record(request):
	if request.user.is_authenticated:
		record_to_edit = Record.objects.get(id = request.POST.get("record_to_edit_id"))
		record_to_edit.for_floor = request.POST.get("for_floor")
		record_to_edit.for_room = request.POST.get("for_room")
		record_to_edit.body = request.POST.get("body")
		record_to_edit.save()
		return render_userpage(request, "Record Edited Successfully!")
	
	
def test(request):
	record = Record.objects.all()
	print(record)
	return HttpResponse("check the console")
	
	
	

supervisor_portal/templates/base.html
<!DOCTYPE html>
<html>

	<head>
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Supervision Portal</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		{% load static %}
		<link rel = "stylesheet" href = '{% static "css/general.css" %}'>
		<script src = '{% static "js/general.js" %}'></script>
		
	</head>

	<body>
	
		{% block content %}
		{% endblock %}
	
	</body>
	
</html>

supervisor_portal/templates/landing.html
{% extends 'base.html' %}

{% block content %}
	
	<div class="jumbotron">
		<h1>Lokamanya Vidya Mandir Trust- Supervision Portal</h1> 
	</div>
	<div class="padding">
		
		<div class="card paper-effect">
		  <div class="card-header">Login:</div>
		  <div class="card-body">
			<form class="form-horizontal" method="POST" action="/supervisor_portal/login">
				{% csrf_token %}
				<div class="form-group">
					<label class="control-label col-sm-2" for="username">Username:</label>
					<input type="text" name="username" class="form-control" id="id_username">
				  </div>
				  <div class="form-group">
					<label class="control-label col-sm-2" for="pwd">Password:</label>
					<input type="password" name="password" class="form-control" id="pwd">
				  </div>
				  <!--<div class="checkbox">
					<label><input type="checkbox" name="checkbox"> Remember me</label>
				  </div>-->
				  <button type="submit" class="btn btn-primary">Submit</button>
			</form>  
		  </div>
		  {% if message %}
			<div class="card-footer"><span class="warning">{{message}}</span></div>
		{% endif %}
		</div>
		
	
	</div>
{% endblock %}

supervisor_portal/templates/test.html
{% for item in post_data %}
	{{item}}
{% endfor %}

supervisor_portal/templates/userpage.html
{% extends 'base.html' %}
{% block content %}
	<div class="jumbotron">
		<h1>Lokamanya Vidya Mandir Trust- Supervision Portal</h1> 
	</div>

	<div class="padding">
		<h3>Welcome, {{ user.first_name }}</h3>
		<br><br>
		{% if record_form %}
			<div class="card paper-effect">
				<div class="card-header">
					<p>Record: </p>
				</div>
				<div class="card-body">
					<form method = "POST" action = "/supervisor_portal/create_record">
						{% csrf_token %}
						{{ record_form.as_p }}
						<button type = "submit" class = "btn btn-outline-dark">Create Record</button>
					</form>
				</div>
				<div class="card-footer"><small>The Date and Time For Creation of the Records will be Automatically Maintained.</small></div>
			</div>
		{% elif record_to_edit %}
			<div class="card paper-effect">
				<div class="card-header">
					<p>Edit Record: </p>
				</div>
				<div class="card-body">
					<form method = "POST" action = "/supervisor_portal/edit_record">
						{% csrf_token %}
						<input hidden value={{record_to_edit.id}} name="record_to_edit_id">
						<label for="id_for_floor">For floor:</label>
						<input required type="number" name="for_floor" id="id_for_floor" value="{{record_to_edit.for_floor}}"><br><br>
						<label for="id_for_room">For room:</label>
						<input required type="text" name="for_room" id="id_for_room" value="{{record_to_edit.for_room}}"><br><br>
						<label for="id_body">Body:</label>
						<textarea rows=10 cols=40	 required name="body" id="id_body">{{record_to_edit.body}}</textarea><br><br>
						<button type = "submit" class = "btn btn-outline-dark">Edit Record</button>
					</form>
				</div>
				<!--<div class="card-footer"><small>The Date and Time For Creation of the Records will be Automatically Maintained.</small></div>-->
			</div>
		{% endif %}
		
		{% if records %}
			<div class="form-group">
			  <!--<label for="searchBar">Search for a Record:</label>-->
			  <input type="text" class="form-control" id="searchBar" placeholder="Search for a Record...">
			</div>
			<table id = "recordsTable">
				<tr><th>Date</th><th>&nbsp&nbspFloor&nbsp&nbsp</th><th>&nbsp&nbspRoom&nbsp&nbsp</th><th>&nbsp&nbspDescription&nbsp&nbsp</th><th>&nbsp&nbspActions&nbsp&nbsp</th></tr>
				{% for record in records %}
					<tr>
						<td>{{record.date}}</td>
						<td>{{record.for_floor}}</td>
						<td>{{record.for_room}}</td>
						<td>{{record.body}}</td>
						<td>
							<form method = "POST" action="/supervisor_portal/modify_record">
								{% csrf_token %}
								<input name="record_id" hidden type="text" value="{{record.id}}"> 
								<button type="submit" class="btn btn-outline-primary" name="action" value="edit">Edit</button>
								<button type="submit" class="btn btn-outline-danger" name="action" value="delete">Delete</button>
							</form>
						</td>
						</tr>
				{% endfor %}
			</table>
<!--
			<h1 style="color:#e0e0e0;text-align:center;"></h1>-->
		{% endif %}
		
		{% if message %}
			<div class="toast" data-autohide="false">
			  <div class="toast-header">
				<strong class="mr-auto text-primary">Info:</strong>
				<small class="text-muted"></small>
				<button  type="button" class="ml-2 mb-1 close" data-dismiss="toast">&times;</button>
			  </div>
			  <div class="toast-body">
				{{message}}
			  </div>
			</div>	
		{% endif %}
	</div>
	
	<form method = "POST" action = "/supervisor_portal/logout">
		{% csrf_token %}
		<button type = "submit" class = "btn btn-outline-danger" id = "logout_btn">Sign Out</button> 
	</form>
	
	
	
{% endblock %}